# Project configuration
project_id = "your-project-id"
project_name = "rashenal"

[api]
enabled = true
port = 54321

[db]
enabled = true
port = 54322

[studio]
enabled = true
port = 54323

[edge_functions]
enabled = true
port = 54324

[auth]
enabled = true
port = 54325
