
version: '3.8'
services:
  db:
    image: supabase/postgres:15.1.0.89
    ports:
      - "54322:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
